mosquitto:
   image: eclipse-mosquitto
   hostname: mosquitto
   container_name: mosquitto
   expose:
     - "1883"
     - "9001"
   ports:
     - "1883:1883"
     - "9001:9001"
   volumes:
#     - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
     - /var/log/docker/mosquitto:/mosquitto/log
     - ./mosquitto/data:/mosquitto/data
     - /etc/localtime:/etc/localtime:ro
